# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JMT11' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for JMT11
	pod 'NMapsMap'
end
